// NimZero local Sepolia testnet wallets (chainId 11155111).
//
// First run generates a fresh BIP39 mnemonic and stores it in
// `.sepolia/secrets.json` (0600, gitignored — never committed). Two
// dedicated accounts are derived from it:
//   deployer = m/44'/60'/0'/0/0   pays the deploy + mint gas
//   relayer  = m/44'/60'/0'/0/1   pays the relay() settlement gas
//
// DEPLOYER_KEY=0x.. overrides the deployer account if you prefer your own.
// The Nimiq Pay user address is NEVER a signer here — it is only ever passed
// as USER_ADDRESS (a recipient/mint target) and never expects a private key.
//
// Public addresses are printed freely; private keys / the mnemonic are never
// printed by any script and never committed.

const fs = require('node:fs')
const path = require('node:path')
const { Wallet, HDNodeWallet } = require('ethers')

const ROOT = path.join(__dirname, '..', '..')
const SECRETS_DIR = path.join(ROOT, '.sepolia')
const SECRETS_FILE = path.join(SECRETS_DIR, 'secrets.json')
const BASE_PATH = "m/44'/60'/0'/0"
const DEPLOYER_INDEX = 0
const RELAYER_INDEX = 1

function ensureGitignore() {
  const gitignore = path.join(ROOT, '.gitignore')
  let content = ''
  try {
    content = fs.readFileSync(gitignore, 'utf8')
  } catch {
    /* file may not exist */
  }
  if (content.includes('.sepolia/')) return
  fs.appendFileSync(gitignore, '\n# Local Sepolia testnet wallets (mnemonic — never commit)\n.sepolia/\n')
}

function loadOrCreateMnemonic() {
  if (fs.existsSync(SECRETS_FILE)) {
    let data
    try {
      data = JSON.parse(fs.readFileSync(SECRETS_FILE, 'utf8'))
    } catch {
      throw new Error(`[sepolia-wallets] corrupted secrets file at ${SECRETS_FILE} — remove it to regenerate a fresh wallet set`)
    }
    if (typeof data.mnemonic === 'string' && data.mnemonic.length > 0) return data.mnemonic
    throw new Error(`[sepolia-wallets] no mnemonic in ${SECRETS_FILE} — remove it to regenerate`)
  }
  const fresh = Wallet.createRandom()
  fs.mkdirSync(SECRETS_DIR, { recursive: true })
  fs.writeFileSync(SECRETS_FILE, JSON.stringify({ mnemonic: fresh.mnemonic.phrase }, null, 2) + '\n', {
    mode: 0o600
  })
  ensureGitignore()
  console.log('[sepolia-wallets] generated a fresh local wallet pair in .sepolia/secrets.json (0600, gitignored)')
  return fresh.mnemonic.phrase
}

function buildWallet(phrase, index, provider) {
  const hd = HDNodeWallet.fromPhrase(phrase, undefined, BASE_PATH).deriveChild(index)
  return provider ? hd.connect(provider) : hd
}

// Resolve { deployer, relayer } Wallet/Signer pair for a given provider.
// DEPLOYER_KEY (env) overrides the derived deployer account; the relayer is
// always derived from the local secret.
function ensureWallets(provider) {
  const phrase = loadOrCreateMnemonic()
  const overrideKey = process.env.DEPLOYER_KEY
  let deployer
  if (overrideKey) {
    deployer = new Wallet(overrideKey, provider)
    console.log('[sepolia-wallets] using DEPLOYER_KEY env for the deployer account')
  } else {
    deployer = buildWallet(phrase, DEPLOYER_INDEX, provider)
  }
  const relayer = buildWallet(phrase, RELAYER_INDEX, provider)
  return { deployer, relayer, autogenerated: !overrideKey }
}

// Private key for the local relayer account, or null when no secret exists yet.
// Used by the relayer server as a local fallback — callers must handle it as a
// secret (do not log it).
function getRelayerPrivateKey() {
  if (!fs.existsSync(SECRETS_FILE)) return null
  let data
  try {
    data = JSON.parse(fs.readFileSync(SECRETS_FILE, 'utf8'))
  } catch {
    return null
  }
  if (typeof data.mnemonic !== 'string' || data.mnemonic.length === 0) return null
  return buildWallet(data.mnemonic, RELAYER_INDEX, null).privateKey
}

module.exports = { ensureWallets, getRelayerPrivateKey }