// Deploy NimZero's live testnet stack to Ethereum Sepolia:
//   TestUSDT (USDT0-salt-slot-compatible, 6 decimals) + ZeroPayRelay(token)
//
//   USER_ADDRESS=0x.. [AMOUNT=100] npm run deploy:sepolia
//
// NO private key is required from you. On the first run a dedicated local
// wallet pair is generated (scripts/lib/sepolia-wallets.cjs) and stored in
// `.sepolia/secrets.json` (0600, gitignored):
//   • deployer — pays the deploy + mint gas      (fund it with Sepolia ETH)
//   • relayer  — pays the relay() settlement gas (fund it with Sepolia ETH)
//   • USER_ADDRESS (your Nimiq Pay EVM address) is NEVER a signer and stays
//     at 0 ETH — that is the gasless proof.
// DEPLOYER_KEY=0x.. optionally overrides the deployer account.
//
// Prints ONLY public addresses. Private keys / the mnemonic are never printed
// and never committed. After deploying, point the relayer at this stack
// (see README → Live testnet proof).

const { ethers } = require('hardhat')
const { ensureWallets } = require('./lib/sepolia-wallets.cjs')

const USER = process.env.USER_ADDRESS
const AMOUNT = Number(process.env.AMOUNT || 100)
const FAUCET = 'https://www.alchemy.com/faucets/ethereum-sepolia'
const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/
const MIN_GAS = ethers.parseEther('0.03')

const fmt = (big) => Number(ethers.formatEther(big)).toFixed(3)

;(async () => {
  const provider = ethers.provider
  const { deployer, relayer, autogenerated } = ensureWallets(provider)

  const [depBal, relBal] = await Promise.all([
    provider.getBalance(deployer.address),
    provider.getBalance(relayer.address)
  ])

  console.log('\n=== NimZero Sepolia addresses (safe to share) ===')
  console.log('deployer  :', deployer.address)
  console.log('relayer   :', relayer.address)
  console.log('user      :', USER || '(set USER_ADDRESS)')
  console.log('funding   : deployer=' + fmt(depBal) + ' SEP | relayer=' + fmt(relBal) + ' SEP')
  if (autogenerated) {
    console.log('wallet    : auto-generated pair in .sepolia/secrets.json — keys never printed/committed')
  }

  if (!USER) {
    console.error('\n[usage] USER_ADDRESS required — your Nimiq Pay EVM address (recipient/mint target only, never a signer).')
    process.exit(2)
  }
  if (!ADDRESS_RE.test(USER)) {
    console.error('\n[usage] USER_ADDRESS must be 0x + 40 hex characters.')
    process.exit(2)
  }
  if (USER.toLowerCase() === deployer.address.toLowerCase()) {
    console.error('\n[usage] USER_ADDRESS must differ from the deployer — the user keeps 0 ETH.')
    process.exit(2)
  }

  if (depBal < MIN_GAS) {
    console.error('\n[fund] Deployer needs Sepolia ETH to deploy + mint.')
    console.error('  fund    :', deployer.address)
    console.error('  relayer :', relayer.address, '(also needs ETH to settle payments)')
    console.error('  faucet  :', FAUCET)
    process.exit(3)
  }
  if (relBal < MIN_GAS) {
    console.warn('\n[fund] Relayer balance is low (' + fmt(relBal) + ' SEP) — fund it before settling payments.')
    console.warn('  relayer :', relayer.address)
    console.warn('  faucet  :', FAUCET)
  }

  const chainId = (await provider.getNetwork()).chainId
  console.log('\nDeploying on chainId ' + Number(chainId) + ' (Sepolia)...')

  const TestUSDT = await ethers.getContractFactory('TestUSDT', deployer)
  const token = await TestUSDT.deploy('USDT0', 'NIM-USDT')
  await token.waitForDeployment()
  const tokenAddr = await token.getAddress()
  console.log('token     :', tokenAddr, '— NIM-USDT, 6 decimals, USDT0 salt-slot permit')

  const ZeroPayRelay = await ethers.getContractFactory('ZeroPayRelay', deployer)
  const relay = await ZeroPayRelay.deploy(tokenAddr)
  await relay.waitForDeployment()
  const relayAddr = await relay.getAddress()
  console.log('relay     :', relayAddr)

  const amountWei = BigInt(Math.round(AMOUNT * 1e6))
  await (await token.mint(USER, amountWei)).wait()
  console.log('minted    :', AMOUNT, 'NIM-USDT ->', USER, '(their ETH remains 0)')

  const domain = await token.DOMAIN_SEPARATOR()

  console.log('\n=== Sepolia deployment ===')
  console.log('chainId:      ', Number(chainId))
  console.log('deployer:     ', deployer.address)
  console.log('relayer:      ', relayer.address)
  console.log('token:        ', tokenAddr)
  console.log('token symbol: ', await token.symbol())
  console.log('token name:   ', await token.name())
  console.log('domain sep:   ', domain)
  console.log('relay:        ', relayAddr)
  console.log('user:         ', USER)
  console.log('user funded:  ', AMOUNT, 'NIM-USDT (0 ETH)')

  console.log('\nRelayer env (RELAYER_PRIVATE_KEY is derived locally — never printed):')
  console.log(`ZERO_CHAIN_ID=${Number(chainId)}`)
  console.log(`ZERO_NETWORK="Ethereum Sepolia (testnet)"`)
  console.log(`ZERO_TOKEN=${tokenAddr}`)
  console.log(`ZERO_TOKEN_NAME=USDT0`)
  console.log(`ZERO_TOKEN_VERSION=1`)
  console.log(`ZERO_TOKEN_SYMBOL=NIM-USDT`)
  console.log(`ZERO_TOKEN_DECIMALS=6`)
  console.log(`ZERO_SALT_SLOT=1`)
  console.log(`ZERO_EXPLORER_URL=https://sepolia.etherscan.io`)
  console.log(`ZERO_RPC_URL=${process.env.SEPOLIA_RPC_URL || 'https://ethereum-sepolia-rpc.publicnode.com'}`)
  console.log(`RELAY=${relayAddr}`)
  console.log('RELAYER_PRIVATE_KEY=<derived from .sepolia/secrets.json relayer account; set on your host, never in the repo>')
  console.log('\nCheck in Nimiq Pay: switch to Sepolia → NIM-USDT funded → ETH balance 0.')
})().catch((err) => {
  console.error('deploy-sepolia FAILED:', err)
  process.exit(1)
})